services:
  - type: web
    name: taha-bot-md-pro
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /status
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CHANNEL_JID
        sync: false
