services:
  - type: web
    name: taha-khan-bot-md
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /status
    envVars:
      - key: sk-abcdef1234567890abcdef1234567890abcdef12
        sync: false
      - key: AQ.Ab8RN6I3N3Ckuym7_Qx-QfG1kAIA1Key_5i0MseF8M07jegEZg
        sync: false
      - key: 120363409838427367@newsletter
        sync: false
      - key: NODE_ENV
        value: production
    disk:
      name: taha-session
      mountPath: /opt/render/project/src/session
      sizeGB: 1
